On GCC 5, we get the error "undefined reference to dlopen" when the linking flags are set before the files so linking flags have been moved after the files